DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID INTEGER NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    PRIORITY INTEGER NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    CURR VARCHAR(3) NOT NULL
);

CREATE INDEX idx_brand_product_date ON PRICES(BRAND_ID, PRODUCT_ID, START_DATE, END_DATE);
CREATE INDEX idx_priority ON PRICES(PRIORITY);